# Generated by Django 3.1.7 on 2021-03-21 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usage_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_at', models.DateTimeField(verbose_name='Usage At')),
                ('usage_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_usages', to='usage_types.usagetype')),
            ],
        ),
    ]
